version: '2'
services:
  db:
    image: mysql:5.6
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - "./mysql:/etc/mysql/mysql.conf.d"
      - "/tmp/mysql:/var/lib/mysql"

  flow.ci:
    image: flow.ci.backend
    networks:
      - backend
    environment:
      CATALINA_OPTS: $CATALINA_OPTS
      FLOW_API_DOMAIN: $FLOW_API_DOMAIN
      FLOW_WEB_DOMAIN: $FLOW_WEB_DOMAIN
      FLOW_SYS_EMAIL: $FLOW_SYS_EMAIL
      FLOW_SYS_USERNAME: $FLOW_SYS_USERNAME
      FLOW_SYS_PASSWORD: $FLOW_SYS_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - "8080:8080"
      - "2181:2181"
    depends_on:
      - db
    volumes:
      - "./docker:/etc/flow.ci/config"

  flow.web:
    image: flow.web
    networks:
      - backend
    environment:
      - FLOW_API_DOMAIN=http://$FLOW_API_DOMAIN:8080/flow-api
    ports:
      - "3000:80"
    depends_on:
      - flow.ci
networks:
  backend: