version: '3'
services:
  db:
    image: mysql:5.6
    networks:
      - backend
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    expose:
      - 3306

  flow.ci:
    image: flow.ci.backend:0.0.4
    networks:
      - backend
    ports:
      - "8080:8080"
      - "2181:2181"
    depends_on:
      - db

  flow.web:
    image: flow.web:0.0.4
    networks:
      - backend
    ports:
      - "3000:80"
    depends_on:
      - flow.ci
networks:
  backend: