version: '2'
services:

  flow.ci:
    image: flowci/flow-platform
    networks:
      - backend
    environment:
      CATALINA_OPTS: $CATALINA_OPTS
      FLOW_API_DOMAIN: $FLOW_API_DOMAIN
      FLOW_WEB_DOMAIN: $FLOW_WEB_DOMAIN
      FLOW_SYS_EMAIL: $FLOW_SYS_EMAIL
      FLOW_SYS_USERNAME: $FLOW_SYS_USERNAME
      FLOW_SYS_PASSWORD: $FLOW_SYS_PASSWORD
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_HOST: $MYSQL_HOST
    volumes:
      - "~/flow-ci/data:/root/flow-ci"
      - "~/flow-ci/db:/var/lib/mysql"
    ports:
      - "8080:8080"
      - "2181:2181"

  flow.web:
    image: flowci/flow-web
    networks:
      - backend
    environment:
      - FLOW_API_DOMAIN=http://$FLOW_API_DOMAIN:8080/flow-api
    ports:
      - "3000:80"
    depends_on:
      - flow.ci
networks:
  backend:
