## Docker-Compose file is used to start flow.ci services

##### Environment Variables #####
## FLOWCI_SERVER_HOST##
## FLOWCI_RABBIT_HOST ##
## FLOWCI_ZOOKEEPER_HOST ##

version: '3'
services:
  db:
    image: mongo:3.6
    restart: always
    container_name: flowci-db
    ports:
      - "27017:27017"
    volumes:
      - "$FLOWCI_SERVER_DB_DIR:/data/db"
    networks:
      flowci_net:
        ipv4_address: 172.1.3.1

  zk:
    image: zookeeper:3.4
    container_name: flowci-zk
    restart: always
    ports:
      - "2181:2181"
    networks:
      flowci_net:
        ipv4_address: 172.1.3.2

  rabbitmq:
    image: rabbitmq:3-management
    container_name: flowci-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      flowci_net:
        ipv4_address: 172.1.3.3

  minio:
    image: minio/minio
    container_name: flowci-minio
    environment:
      MINIO_ACCESS_KEY: $FLOWCI_DEFAULT_MINIO_ACCESS_KEY
      MINIO_SECRET_KEY: $FLOWCI_DEFAULT_MINIO_SECRET_KEY
    ports:
      - "9000:9000"
    volumes:
      - "$FLOWCI_SERVER_DATA_DIR:/data"
    command: server /data
    networks:
      flowci_net:
        ipv4_address: 172.1.3.4

  core:
    image: flowci/core
    container_name: flowci-core
    ports:
      - "8080:8080"
    volumes:
      - "$FLOWCI_SERVER_DIR:/root/.flow.ci"
    environment:
      FLOWCI_LOG_LEVEL: INFO
      FLOWCI_SERVER_PORT: 8080
      FLOWCI_SERVER_ADDRESS: 0.0.0.0
      FLOWCI_DEFAULT_ADMIN_EMAIL: $FLOWCI_DEFAULT_ADMIN_EMAIL
      FLOWCI_DEFAULT_ADMIN_PASSWORD: $FLOWCI_DEFAULT_ADMIN_PASSWORD
      FLOWCI_MONGODB_URI: mongodb://db:27017/flow_ci_db
      FLOWCI_RABBITMQ_URI: amqp://guest:guest@rabbitmq:5672
      FLOWCI_MINIO_ENDPOINT: http://minio:9000
      FLOWCI_MINIO_KEY: $FLOWCI_DEFAULT_MINIO_ACCESS_KEY
      FLOWCI_MINIO_SECRET: $FLOWCI_DEFAULT_MINIO_SECRET_KEY
      FLOWCI_ZK_HOST: zk

      # config host for agent
      FLOWCI_SERVER_HOST: $FLOWCI_SERVER_HOST
      FLOWCI_RABBIT_HOST: $FLOWCI_RABBIT_HOST
      FLOWCI_ZOOKEEPER_HOST: $FLOWCI_ZOOKEEPER_HOST
    command: [
      "./wait_for_it.sh", 
      "rabbitmq:5672", 
      "-t", "0", 
      "--strict", "--",
      "java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", 
      "-Xms1500m", "-Xmx1500m", "-jar", "flow-ci-core.jar"
    ]
    depends_on:
      - rabbitmq
      - db
      - zk
      - minio
    networks:
      flowci_net:
        ipv4_address: 172.1.2.1

  web:
    image: flowci/web
    container_name: flowci-web
    ports:
      - "2015:2015"
    environment:
      FLOWCI_SERVER_URL: http://${FLOWCI_SERVER_HOST}:8080
    networks:
      flowci_net:
        ipv4_address: 172.1.1.1

networks:
  flowci_net:
    ipam:
      driver: default
      config:
        - subnet: "172.1.0.0/16"